name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Run tests
        run: cargo test --workspace --all-features --verbose
