name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.changes.outputs.rust }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'

  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/trunk-action@v1

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: changes
    if: needs.changes.outputs.rust == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked
      - name: Run tests with nextest (JUnit output)
        run: cargo nextest run --profile ci
      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: target/nextest/ci/junit.xml
      - name: Upload results to Trunk Analytics
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        continue-on-error: true
        with:
          junit-paths: target/nextest/ci/junit.xml
          org-slug: arch-protogens
          token: ${{ secrets.TRUNK_API_TOKEN }}
